- name: Load another yml file
  hosts: localhost
  connection: local
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World

    - name: Include Universe file
      ansible.builtin.import_tasks:
        file: universe.yml
