- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Print all fruits
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - apple
        - blueberry
        - guava
        - grapes
        - oranges
