- name: Demo on register
  hosts: localhost
  connection: local
  tasks:
    - name: Storing uptime
      ansible.builtin.shell: uptime
      register: output

    - name: Print register value
      ansible.builtin.debug:
        msg: "{{ output.stdout | split(' ') }}"